
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Danillo
 */
public class ManipularNotas extends javax.swing.JFrame {

    /**
     * Creates new form ManipularNotas
     */
    public ManipularNotas() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        cabecalho8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        voltar8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boletim = new javax.swing.JTable();
        atualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 102, 51));

        cabecalho8.setBackground(new java.awt.Color(255, 255, 255));
        cabecalho8.setFont(new java.awt.Font("Monotype Corsiva", 1, 100)); // NOI18N
        cabecalho8.setForeground(new java.awt.Color(255, 255, 255));
        cabecalho8.setText("Notas");

        voltar8.setText("Voltar");
        voltar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar8ActionPerformed(evt);
            }
        });

        boletim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Materia", "BIM 1", "BIM 2", "R1", "BIM 3", "BIM 4", "R2", "R FINAL", "POSSIBILIDADE", "Status"
            }
        ));
        boletim.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                boletimAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(boletim);

        atualizar.setText("Atualizar Notas");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator10)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(cabecalho8)
                        .addGap(0, 361, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cabecalho8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltar8)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar8ActionPerformed
        DocenteLogado dl = new DocenteLogado();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltar8ActionPerformed

    private void boletimAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_boletimAncestorAdded

        matricula = JOptionPane.showInputDialog("Digite a MATRICULA do Aluno: ");
        disciplina = JOptionPane.showInputDialog("Digite a Disciplina: ");
        bimestre = Integer.parseInt(JOptionPane.showInputDialog("Digite o Bimestre Atual: "));

        AlunoDB a = new AlunoDB();
        if (!a.verificarAntesDeCadastrar(matricula)) {
            MateriasDB mdb = new MateriasDB();
            Materias m = new Materias(0.0, 0.0, 0.0, 0.0, 0.0, 0.0 , 0.0, 0.0, disciplina, bimestre, matricula);
            
            if (!mdb.verificaCadastroMateria(disciplina, matricula)) {
                
                mdb.inserir(m);
            }
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getNome(), 0, 0);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getBim1(), 0, 1);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getBim2(), 0, 2);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getR1(), 0, 3);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getBim3(), 0, 4);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getBim4(), 0, 5);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getR2(), 0, 6);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getRf(), 0, 7);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getPossibilidade(), 0, 8);
            boletim.setValueAt(mdb.retonarNotas(matricula, disciplina).getStatus(), 0, 9);
            
        }else{
            JOptionPane.showMessageDialog(null, "MATRICULA Incorreta! Verifique os Dados e Tente Novamente!");
            ManipularNotas mn = new ManipularNotas();
            mn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_boletimAncestorAdded

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        
        String valores[] = new String[11];
        
        for(int i=0; i<10; i++){
            valores[i] = boletim.getValueAt(0, i).toString();
            
        }
        
        Materias m1 = new Materias(Double.parseDouble(valores[1]),Double.parseDouble(valores[2]),
                Double.parseDouble(valores[4]),Double.parseDouble(valores[5]),Double.parseDouble(valores[3]),
                Double.parseDouble(valores[6]),Double.parseDouble(valores[7]),Double.parseDouble(valores[8]),
                disciplina,bimestre, valores[9],matricula);
        m1.reposicao();
        m1.statusAtual();
        m1.possibilidade();        
        m1.RecuperacaoFinal();
        
        MateriasDB mdb = new MateriasDB();
        if(mdb.verificaCadastroMateria(disciplina, matricula)){
            mdb.atualizar(m1);
            JOptionPane.showMessageDialog(null,"Operacao Realizada com Sucesso!!");
        }else{
            System.out.println("Matricula errada, Tente Novamente!");
        }
        
    }//GEN-LAST:event_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipularNotas().setVisible(true);
            }
        });
    }
    private String disciplina, matricula;
    private int bimestre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JTable boletim;
    private javax.swing.JLabel cabecalho8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JButton voltar8;
    // End of variables declaration//GEN-END:variables
}
